name: CD

on:
    - pull_request

jobs:
    build_and_push:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u frankh --password-stdin
      - name: build
        run: docker build -t frankh/witw:pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH") .
      - name: push
        run: docker push frankh/witw:pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

    deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install helm
        run: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'witw'
          location: 'europe-west2'
      - name: deploy
        run: helm upgrade --wait --install --create-namespace -n witw-pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH") witw --set hostname=witw-pr-$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH").posthog.shawabawa.com --version 0.10.0 oci://registry-1.docker.io/frankh/witw

